# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.    The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.7.6
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from lunchable.models.currency_enum import CurrencyEnum
from typing import Set
from typing_extensions import Self


class BulkUpdateTransactionsObject(BaseModel):
    """
    BulkUpdateTransactionsObject
    """  # noqa: E501

    var_date: Optional[date] = Field(
        default=None,
        description="New date for all transactions in ISO 8601 format",
        alias="date",
    )
    payee: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=140)]
    ] = Field(default=None, description="New payee for all transactions. ")
    category_id: Optional[StrictInt] = Field(
        default=None,
        description="Unique identifier of the new category to assign to all transactions. Set this to 0 to un-categorize all transactions.",
    )
    notes: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=350)]
    ] = Field(
        default=None,
        description="A new notes for all transactions. Set this to an empty string to remove all existing notes. ",
    )
    currency: Optional[CurrencyEnum] = Field(
        default=None,
        description='Three-letter lowercase currency code in ISO 4217 format for all transactions.<br> This cannot be set if any of the transactions belong to a synced account whose "Allow Modifications to Transactions" property is not set.',
    )
    manual_account_id: Optional[StrictInt] = Field(
        default=None,
        description='The unique identifier of the manual account to associate all transactions with.  Should not be set if `plaid_account_id` is also be set, unless both properties are set to 0 in which case the transactions will have no account and be displayed as "Cash Transactions".<br> This cannot be set if any of the transactions belong to a synced account whose "Allow Modifications to Transactions" property is not set.',
    )
    plaid_account_id: Optional[StrictInt] = Field(
        default=None,
        description='The unique identifier of the plaid synced account to associate all transactions with.  Should not be set if `manual_account_id` is also be set, unless both properties are set to 0 in which case the transactions will have no account and be displayed as "Cash Transactions". <br> This cannot be set if any of the transactions belong to a synced account whose "Allow Modifications to Transactions" property is not set. Similarly existing transactions cannot be moved to to an existing Plaid account without this property.',
    )
    tag_ids: Optional[List[StrictInt]] = Field(
        default=None,
        description="A list of tag_ids for tags to associated with all transactions.  If set, this property will overwrite any existing tags.  Use `additional_tag_ids` to add tags to the existing transactions' tags.  Set this to an empty array to remove all tags from a transaction. If set `additional_tag_ids` may not be set.",
    )
    additional_tag_ids: Optional[List[StrictInt]] = Field(
        default=None,
        description="A list of tag_ids for the tags associated with this transaction.  If set, the tags listed in this property be added to any existing transaction tags. Use `tag_ids` to overwrite or clear transaction tags. If set `tag_ids` may not be set.",
    )
    status: Optional[StrictStr] = Field(
        default=None,
        description="Updated status for all of the transactions, may be one of: - `reviewed`: User has reviewed the transaction - `unreviewed`: User has not reviewed the transaction ",
    )
    __properties: ClassVar[List[str]] = [
        "date",
        "payee",
        "category_id",
        "notes",
        "currency",
        "manual_account_id",
        "plaid_account_id",
        "tag_ids",
        "additional_tag_ids",
        "status",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["reviewed", "unreviewed"]):
            raise ValueError("must be one of enum values ('reviewed', 'unreviewed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BulkUpdateTransactionsObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if category_id (nullable) is None
        # and model_fields_set contains the field
        if self.category_id is None and "category_id" in self.model_fields_set:
            _dict["category_id"] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict["notes"] = None

        # set to None if manual_account_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.manual_account_id is None
            and "manual_account_id" in self.model_fields_set
        ):
            _dict["manual_account_id"] = None

        # set to None if plaid_account_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.plaid_account_id is None
            and "plaid_account_id" in self.model_fields_set
        ):
            _dict["plaid_account_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BulkUpdateTransactionsObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "date": obj.get("date"),
                "payee": obj.get("payee"),
                "category_id": obj.get("category_id"),
                "notes": obj.get("notes"),
                "currency": obj.get("currency"),
                "manual_account_id": obj.get("manual_account_id"),
                "plaid_account_id": obj.get("plaid_account_id"),
                "tag_ids": obj.get("tag_ids"),
                "additional_tag_ids": obj.get("additional_tag_ids"),
                "status": obj.get("status"),
            }
        )
        return _obj
