# coding: utf-8

"""
Lunch Money API - v2

This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.  The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.7.4
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self


class CreateNewTransactionsRequest(BaseModel):
    """
    CreateNewTransactionsRequest
    """  # noqa: E501

    transactions: List[InsertTransactionObject] = Field(
        description="List of transactions to insert."
    )
    apply_rules: Optional[StrictBool] = Field(
        default=False,
        description="If set to true, any rules associated with the account specified by the `manual_account_id` property for each transaction will be applied.",
    )
    skip_duplicates: Optional[StrictBool] = Field(
        default=False,
        description="If set to true, the system will flag new transactions that have the same `date`, `payee`, `amount`, and `manual_account_id`, as a duplicate.   Not that deduplication based on `external_id` and `manual_account_id` will always occur regardless of how this property is set.",
    )
    skip_balance_update: Optional[StrictBool] = Field(
        default=False,
        description="If set to true, and new transactions include a `manual_account_id`, the balances of these accounts will not be updated, when the transactions are inserted.",
    )
    __properties: ClassVar[List[str]] = [
        "transactions",
        "apply_rules",
        "skip_duplicates",
        "skip_balance_update",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateNewTransactionsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item_transactions in self.transactions:
                if _item_transactions:
                    _items.append(_item_transactions.to_dict())
            _dict["transactions"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateNewTransactionsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "transactions": [
                    InsertTransactionObject.from_dict(_item)
                    for _item in obj["transactions"]
                ]
                if obj.get("transactions") is not None
                else None,
                "apply_rules": obj.get("apply_rules")
                if obj.get("apply_rules") is not None
                else False,
                "skip_duplicates": obj.get("skip_duplicates")
                if obj.get("skip_duplicates") is not None
                else False,
                "skip_balance_update": obj.get("skip_balance_update")
                if obj.get("skip_balance_update") is not None
                else False,
            }
        )
        return _obj
