# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing_extensions import Annotated, Self

from lunchable.models.create_category_request_object_children_inner import (
    CreateCategoryRequestObjectChildrenInner,
)


class CreateCategoryRequestObject(BaseModel):
    """
    CreateCategoryRequestObject
    """  # noqa: E501

    name: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(
        description="The name of the new category. Must be between 1 and 100 characters. Must not match the name of any existing categories or category groups."
    )
    description: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=200)]
    ] = Field(
        default=None,
        description="The description of the category. Must not exceed 200 characters.",
    )
    is_income: Optional[StrictBool] = Field(
        default=False,
        description="If true, the transactions in this category will be treated as income.",
    )
    exclude_from_budget: Optional[StrictBool] = Field(
        default=False,
        description="If true, the transactions in this category will be excluded from the budget.",
    )
    exclude_from_totals: Optional[StrictBool] = Field(
        default=False,
        description="If true, the transactions in this category will be excluded from totals.",
    )
    is_group: Optional[StrictBool] = Field(
        default=False,
        description="If true, the category is a group that can be a parent to other categories, but may not be assigned directly to transactions.",
    )
    group_id: Optional[StrictInt] = Field(
        default=None,
        description="If set to the ID of an existing category group, this new category will be assigned to that group. Cannot be set if `is_group` is true.",
    )
    archived: Optional[StrictBool] = Field(
        default=False,
        description="If true, the category is archived and not displayed in relevant areas of the Lunch Money app.",
    )
    children: Optional[List[CreateCategoryRequestObjectChildrenInner]] = Field(
        default=None,
        description='The list of existing category objects, or existing category IDs or names of new categories to add to the new category group. This attribute should only be set if "is_group" is also set to true.<br> The categories or IDs specified must already exist and may not be category groups themselves. Categories that already belong to another category group will be moved. If strings are specified, they will be used as the names of new categories that will be added to the new category group. The request will fail if any names are the same as the name of an existing category.<br> It is permissible to provide both full category objects and IDs as well as strings for names in the same request.',
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "description",
        "is_income",
        "exclude_from_budget",
        "exclude_from_totals",
        "is_group",
        "group_id",
        "archived",
        "children",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCategoryRequestObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict["children"] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        # set to None if group_id (nullable) is None
        # and model_fields_set contains the field
        if self.group_id is None and "group_id" in self.model_fields_set:
            _dict["group_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCategoryRequestObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "description": obj.get("description"),
                "is_income": obj.get("is_income")
                if obj.get("is_income") is not None
                else False,
                "exclude_from_budget": obj.get("exclude_from_budget")
                if obj.get("exclude_from_budget") is not None
                else False,
                "exclude_from_totals": obj.get("exclude_from_totals")
                if obj.get("exclude_from_totals") is not None
                else False,
                "is_group": obj.get("is_group")
                if obj.get("is_group") is not None
                else False,
                "group_id": obj.get("group_id"),
                "archived": obj.get("archived")
                if obj.get("archived") is not None
                else False,
                "children": [
                    CreateCategoryRequestObjectChildrenInner.from_dict(_item)
                    for _item in obj["children"]
                ]
                if obj.get("children") is not None
                else None,
            }
        )
        return _obj
