# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.  The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, ValidationError, field_validator
from typing import Any, Optional
from lunchable.models.aligned_summary_response_object import (
    AlignedSummaryResponseObject,
)
from lunchable.models.non_aligned_summary_response_object import (
    NonAlignedSummaryResponseObject,
)
from typing import Union, Set, Dict
from typing_extensions import Self

GETBUDGETSUMMARY200RESPONSE_ONE_OF_SCHEMAS = [
    "AlignedSummaryResponseObject",
    "NonAlignedSummaryResponseObject",
]


class GetBudgetSummary200Response(BaseModel):
    """
    GetBudgetSummary200Response
    """

    # data type: AlignedSummaryResponseObject
    oneof_schema_1_validator: Optional[AlignedSummaryResponseObject] = None
    # data type: NonAlignedSummaryResponseObject
    oneof_schema_2_validator: Optional[NonAlignedSummaryResponseObject] = None
    actual_instance: Optional[
        Union[AlignedSummaryResponseObject, NonAlignedSummaryResponseObject]
    ] = None
    one_of_schemas: Set[str] = {
        "AlignedSummaryResponseObject",
        "NonAlignedSummaryResponseObject",
    }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = GetBudgetSummary200Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: AlignedSummaryResponseObject
        if not isinstance(v, AlignedSummaryResponseObject):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `AlignedSummaryResponseObject`"
            )
        else:
            match += 1
        # validate data type: NonAlignedSummaryResponseObject
        if not isinstance(v, NonAlignedSummaryResponseObject):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `NonAlignedSummaryResponseObject`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in GetBudgetSummary200Response with oneOf schemas: AlignedSummaryResponseObject, NonAlignedSummaryResponseObject. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in GetBudgetSummary200Response with oneOf schemas: AlignedSummaryResponseObject, NonAlignedSummaryResponseObject. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into AlignedSummaryResponseObject
        try:
            instance.actual_instance = AlignedSummaryResponseObject.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into NonAlignedSummaryResponseObject
        try:
            instance.actual_instance = NonAlignedSummaryResponseObject.from_json(
                json_str
            )
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into GetBudgetSummary200Response with oneOf schemas: AlignedSummaryResponseObject, NonAlignedSummaryResponseObject. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into GetBudgetSummary200Response with oneOf schemas: AlignedSummaryResponseObject, NonAlignedSummaryResponseObject. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> Optional[
        Union[
            Dict[str, Any],
            AlignedSummaryResponseObject,
            NonAlignedSummaryResponseObject,
        ]
    ]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
