# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from lunchable.models.skipped_existing_external_id_object import (
    SkippedExistingExternalIdObject,
)
from lunchable.models.transaction_object import TransactionObject


class InsertTransactionsResponseObject(BaseModel):
    """
    The object returned from a successful POST /transactions request
    """  # noqa: E501

    transactions: List[TransactionObject] = Field(
        description="An array of the inserted transactions."
    )
    skipped_duplicates: List[SkippedExistingExternalIdObject] = Field(
        description="An array of the requested transactions that were duplicates of existing transactions and were not inserted."
    )
    __properties: ClassVar[List[str]] = ["transactions", "skipped_duplicates"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InsertTransactionsResponseObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item_transactions in self.transactions:
                if _item_transactions:
                    _items.append(_item_transactions.to_dict())
            _dict["transactions"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in skipped_duplicates (list)
        _items = []
        if self.skipped_duplicates:
            for _item_skipped_duplicates in self.skipped_duplicates:
                if _item_skipped_duplicates:
                    _items.append(_item_skipped_duplicates.to_dict())
            _dict["skipped_duplicates"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InsertTransactionsResponseObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "transactions": [
                    TransactionObject.from_dict(_item) for _item in obj["transactions"]
                ]
                if obj.get("transactions") is not None
                else None,
                "skipped_duplicates": [
                    SkippedExistingExternalIdObject.from_dict(_item)
                    for _item in obj["skipped_duplicates"]
                ]
                if obj.get("skipped_duplicates") is not None
                else None,
            }
        )
        return _obj
