# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing_extensions import Annotated, Self

from lunchable.models.currency_enum import CurrencyEnum
from lunchable.models.insert_transaction_object_amount import (
    InsertTransactionObjectAmount,
)


class InsertTransactionObject(BaseModel):
    """
    InsertTransactionObject
    """  # noqa: E501

    var_date: date = Field(
        description="Date of transaction in ISO 8601 format", alias="date"
    )
    amount: InsertTransactionObjectAmount
    currency: Optional[CurrencyEnum] = Field(
        default=None,
        description="Three-letter lowercase currency code of the transaction in ISO 4217 format. Must match one of the [supported currencies](). If not set defaults to the user account's primary currency.",
    )
    payee: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=140)]
    ] = Field(default=None, description="Name of payee for the transaction.")
    category_id: Optional[StrictInt] = Field(
        default=None,
        description="The ID of the category associated with the transactions. If set, the category ID must exist for the user's account and it cannot be a category group.",
    )
    notes: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=350)]
    ] = Field(
        default=None,
        description="Any transaction notes set by the user or by  a matched recurring item. This will match the value  displayed in notes field on the transactions page in the GUI. ",
    )
    manual_account_id: Optional[StrictInt] = Field(
        default=None,
        description='The Unique identifier for the associated manually managed account. If set, this must match an existing manual account id associated with the user\'s account. If not set, and `plaid_account_id` is also not set, no account is associated with the transaction and it will appear as a "Cash Transaction" in the Lunch Money GUI. It is an error if this, and `plaid_account_id` is also set on the same transaction.',
    )
    plaid_account_id: Optional[StrictInt] = Field(
        default=None,
        description='The Unique identifier for the associated plaid synced account. If set, this must match an existing plaid account id associated with the user\'s account. If not set, and `manual_account_id` is also not set, no account is associated with the transaction and it will appear as a "Cash Transaction" in the Lunch Money GUI. It is an error if this, and `manual_account_id` is also set on the same transaction. In addition the specified plaid account must have the "Allow Modifications To Transactions" property set (which is enabled by default), or the insert will fail.',
    )
    recurring_id: Optional[StrictInt] = Field(
        default=None,
        description="Unique identifier for associated recurring item. Recurring item must be associated with the same account.",
    )
    status: Optional[StrictStr] = Field(
        default=None,
        description="If set must be either `reviewed` or `unreviewed`. If not set, defaults to `unreviewed`.",
    )
    tag_ids: Optional[List[StrictInt]] = Field(
        default=None,
        description="A list of IDs for the tags associated with this transaction. Each ID must match an existing tag associated with the user's account. If not set, no tags will be associated with the created transaction.",
    )
    external_id: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=75)]
    ] = Field(
        default=None,
        description="A user-defined external ID for the transaction. If set, and `manual_account_id` is set, the creation of the new transaction will fail if a transaction with this id already exists for the specified manual account.",
    )
    custom_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="An optional JSON object that includes additional data related to this transaction. This must be a valid JSON object and, when stringified, must not exceed 4096 characters. This data may be available in the future for processing by rules.",
    )
    __properties: ClassVar[List[str]] = [
        "date",
        "amount",
        "currency",
        "payee",
        "category_id",
        "notes",
        "manual_account_id",
        "plaid_account_id",
        "recurring_id",
        "status",
        "tag_ids",
        "external_id",
        "custom_metadata",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["reviewed", "unreviewed"]):
            raise ValueError("must be one of enum values ('reviewed', 'unreviewed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InsertTransactionObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict["amount"] = self.amount.to_dict()
        # set to None if category_id (nullable) is None
        # and model_fields_set contains the field
        if self.category_id is None and "category_id" in self.model_fields_set:
            _dict["category_id"] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict["notes"] = None

        # set to None if manual_account_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.manual_account_id is None
            and "manual_account_id" in self.model_fields_set
        ):
            _dict["manual_account_id"] = None

        # set to None if plaid_account_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.plaid_account_id is None
            and "plaid_account_id" in self.model_fields_set
        ):
            _dict["plaid_account_id"] = None

        # set to None if recurring_id (nullable) is None
        # and model_fields_set contains the field
        if self.recurring_id is None and "recurring_id" in self.model_fields_set:
            _dict["recurring_id"] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict["external_id"] = None

        # set to None if custom_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.custom_metadata is None and "custom_metadata" in self.model_fields_set:
            _dict["custom_metadata"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InsertTransactionObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "date": obj.get("date"),
                "amount": InsertTransactionObjectAmount.from_dict(obj["amount"])
                if obj.get("amount") is not None
                else None,
                "currency": obj.get("currency"),
                "payee": obj.get("payee"),
                "category_id": obj.get("category_id"),
                "notes": obj.get("notes"),
                "manual_account_id": obj.get("manual_account_id"),
                "plaid_account_id": obj.get("plaid_account_id"),
                "recurring_id": obj.get("recurring_id"),
                "status": obj.get("status"),
                "tag_ids": obj.get("tag_ids"),
                "external_id": obj.get("external_id"),
                "custom_metadata": obj.get("custom_metadata"),
            }
        )
        return _obj
