# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from lunchable.models.split_transaction_object_amount import (
    SplitTransactionObjectAmount,
)
from typing import Set
from typing_extensions import Self


class SplitTransactionObject(BaseModel):
    """
    The object representing a split transaction
    """  # noqa: E501

    amount: SplitTransactionObjectAmount
    payee: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=140)]
    ] = Field(
        default=None,
        description="The payee for the child transaction. Will inherit the original payee from the parent if not defined.",
    )
    var_date: Optional[date] = Field(
        default=None,
        description="Must be in ISO 8601 format (YYYY-MM-DD). Will inherit from the parent if not defined.",
        alias="date",
    )
    category_id: Optional[StrictInt] = Field(
        default=None,
        description="Unique identifier for associated category_id. Category must already exist for the account. Will inherit category from the parent if not defined.",
    )
    notes: Optional[Annotated[str, Field(strict=True, max_length=350)]] = Field(
        default=None, description="Will inherit notes from parent if not defined."
    )
    __properties: ClassVar[List[str]] = [
        "amount",
        "payee",
        "date",
        "category_id",
        "notes",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SplitTransactionObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict["amount"] = self.amount.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SplitTransactionObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "amount": SplitTransactionObjectAmount.from_dict(obj["amount"])
                if obj.get("amount") is not None
                else None,
                "payee": obj.get("payee"),
                "date": obj.get("date"),
                "category_id": obj.get("category_id"),
                "notes": obj.get("notes"),
            }
        )
        return _obj
