# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Set
from typing_extensions import Self


class SummaryTotalsBreakdownObject(BaseModel):
    """
    SummaryTotalsBreakdownObject
    """  # noqa: E501

    other_activity: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total amount, in the user's default currency, of non recurring activity for the given date range.",
    )
    recurring_activity: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total amount, in the user's default currency, of recurring activity that has occurred for the given date range.",
    )
    recurring_remaining: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total amount, in the user's default currency, of expected recurring activity that has not yet occurred.",
    )
    uncategorized: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total amount, in the user's default currency, of non recurring activity coming from un-categorized transactions.",
    )
    uncategorized_count: Optional[StrictInt] = Field(
        default=None,
        description="Number of un-categorized transactions for the given date range.",
    )
    uncategorized_recurring: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Total amount, in the user's default currency, of recurring activity coming from un-categorized transactions.",
    )
    __properties: ClassVar[List[str]] = [
        "other_activity",
        "recurring_activity",
        "recurring_remaining",
        "uncategorized",
        "uncategorized_count",
        "uncategorized_recurring",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SummaryTotalsBreakdownObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SummaryTotalsBreakdownObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "other_activity": obj.get("other_activity"),
                "recurring_activity": obj.get("recurring_activity"),
                "recurring_remaining": obj.get("recurring_remaining"),
                "uncategorized": obj.get("uncategorized"),
                "uncategorized_count": obj.get("uncategorized_count"),
                "uncategorized_recurring": obj.get("uncategorized_recurring"),
            }
        )
        return _obj
