# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
)
from typing import Any, ClassVar, Dict, List, Optional, Union
from lunchable.models.currency_enum import CurrencyEnum
from typing import Set
from typing_extensions import Self


class SummaryCategoryOccurrenceObject(BaseModel):
    """
    Per period budget activity for the each budget period within the given date range.<br> This is only returned if the query parameter `include_occurrences` is set to `true`.
    """  # noqa: E501

    current: StrictBool = Field(
        description="true if this occurrence is the current budget period."
    )
    start_date: date = Field(description="The start date of the budget period.")
    end_date: date = Field(description="The end date of the budget period.")
    other_activity: Union[StrictFloat, StrictInt] = Field(
        description="Total non recurring activity, in the user's default currency, for the category within the given date range. The total activity for the category is the sum of this and the recurring_activity."
    )
    recurring_activity: Union[StrictFloat, StrictInt] = Field(
        description="Total recurring activity, in the user's default currency, for the category within the given date range. The total activity for the category is the sum of this and the other_activity."
    )
    budgeted: Optional[Union[StrictFloat, StrictInt]] = Field(
        description="Total budgeted amount, in the user's default currency, for the category within the given date range, or null if the category is not budgeted."
    )
    budgeted_amount: Optional[StrictStr] = Field(
        description="Total budgeted amount in the budgeted currency for the category within the given date or null if the category is not budgeted."
    )
    budgeted_currency: Optional[CurrencyEnum] = Field(
        description="Currency of the budgeted amount."
    )
    notes: Optional[StrictStr] = Field(
        description="Any notes added in the Web UI for the budget period."
    )
    __properties: ClassVar[List[str]] = [
        "current",
        "start_date",
        "end_date",
        "other_activity",
        "recurring_activity",
        "budgeted",
        "budgeted_amount",
        "budgeted_currency",
        "notes",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SummaryCategoryOccurrenceObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if budgeted (nullable) is None
        # and model_fields_set contains the field
        if self.budgeted is None and "budgeted" in self.model_fields_set:
            _dict["budgeted"] = None

        # set to None if budgeted_amount (nullable) is None
        # and model_fields_set contains the field
        if self.budgeted_amount is None and "budgeted_amount" in self.model_fields_set:
            _dict["budgeted_amount"] = None

        # set to None if budgeted_currency (nullable) is None
        # and model_fields_set contains the field
        if (
            self.budgeted_currency is None
            and "budgeted_currency" in self.model_fields_set
        ):
            _dict["budgeted_currency"] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict["notes"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SummaryCategoryOccurrenceObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "current": obj.get("current"),
                "start_date": obj.get("start_date"),
                "end_date": obj.get("end_date"),
                "other_activity": obj.get("other_activity"),
                "recurring_activity": obj.get("recurring_activity"),
                "budgeted": obj.get("budgeted"),
                "budgeted_amount": obj.get("budgeted_amount"),
                "budgeted_currency": obj.get("budgeted_currency"),
                "notes": obj.get("notes"),
            }
        )
        return _obj
