# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date, datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Annotated, Self

from lunchable.models.account_type_enum import AccountTypeEnum
from lunchable.models.create_manual_account_request_object_balance import (
    CreateManualAccountRequestObjectBalance,
)
from lunchable.models.currency_enum import CurrencyEnum


class UpdateManualAccountRequestObject(BaseModel):
    """
    UpdateManualAccountRequestObject
    """  # noqa: E501

    id: Optional[StrictInt] = Field(
        default=None,
        description="System defined unique identifier of this account. Ignored if set.",
    )
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=45)]] = (
        Field(default=None, description="If set the new name of the account.")
    )
    type: Optional[AccountTypeEnum] = Field(
        default=None, description="If set the new primary type of the account."
    )
    subtype: Optional[
        Annotated[str, Field(min_length=1, strict=True, max_length=100)]
    ] = Field(
        default=None,
        description="If set an optional account subtype. Examples include<br> - retirement - checking - savings - prepaid credit card",
    )
    display_name: Optional[StrictStr] = Field(
        default=None,
        description="If set, an optional display name for the account.<br> This must be unique for the user.  If not set, it will be derived from the `institution_name` (if any) concatenated with the `name`.",
    )
    balance: Optional[CreateManualAccountRequestObjectBalance] = None
    balance_as_of: Optional[StrictStr] = Field(
        default=None,
        description="A new date for the `updated_at` property. May be set as a date, ie: YYYY-MM-DD, or date-time string in ISO 8601 extended format. This property is ignored if `balance` is not also set. If `balance` is set and this property is not set the current time is used.",
    )
    closed_on: Optional[date] = Field(
        default=None,
        description="If set, the date this account was closed in YYYY-MM-DD format.",
    )
    currency: Optional[CurrencyEnum] = Field(
        default=None,
        description="If set, the new three-letter lowercase currency code of the account balance.",
    )
    institution_name: Optional[
        Annotated[str, Field(min_length=1, strict=True, max_length=50)]
    ] = Field(
        default=None, description="If set, the name of institution holding the account."
    )
    external_id: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=75)]
    ] = Field(
        default=None,
        description="An optional external_id that may be set or updated via the API",
    )
    custom_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="An optional JSON object that includes additional data related to this account. This must be a valid JSON object and, when stringified, must not exceed 4096 characters.",
    )
    exclude_from_transactions: Optional[StrictBool] = Field(
        default=None,
        description="If set, this will indicate if this account will not show up as an option for assignment when creating transactions manually.",
    )
    created_at: Optional[datetime] = Field(
        default=None,
        description="System defined date/time the account was created in ISO 8601 extended format. Ignored if set.",
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="System defined date/time the account was created in ISO 8601 extended format. Ignored if set.",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "name",
        "type",
        "subtype",
        "display_name",
        "balance",
        "balance_as_of",
        "closed_on",
        "currency",
        "institution_name",
        "external_id",
        "custom_metadata",
        "exclude_from_transactions",
        "created_at",
        "updated_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateManualAccountRequestObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of balance
        if self.balance:
            _dict["balance"] = self.balance.to_dict()
        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict["display_name"] = None

        # set to None if balance_as_of (nullable) is None
        # and model_fields_set contains the field
        if self.balance_as_of is None and "balance_as_of" in self.model_fields_set:
            _dict["balance_as_of"] = None

        # set to None if closed_on (nullable) is None
        # and model_fields_set contains the field
        if self.closed_on is None and "closed_on" in self.model_fields_set:
            _dict["closed_on"] = None

        # set to None if institution_name (nullable) is None
        # and model_fields_set contains the field
        if (
            self.institution_name is None
            and "institution_name" in self.model_fields_set
        ):
            _dict["institution_name"] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict["external_id"] = None

        # set to None if custom_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.custom_metadata is None and "custom_metadata" in self.model_fields_set:
            _dict["custom_metadata"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateManualAccountRequestObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "type": obj.get("type"),
                "subtype": obj.get("subtype"),
                "display_name": obj.get("display_name"),
                "balance": CreateManualAccountRequestObjectBalance.from_dict(
                    obj["balance"]
                )
                if obj.get("balance") is not None
                else None,
                "balance_as_of": obj.get("balance_as_of"),
                "closed_on": obj.get("closed_on"),
                "currency": obj.get("currency"),
                "institution_name": obj.get("institution_name"),
                "external_id": obj.get("external_id"),
                "custom_metadata": obj.get("custom_metadata"),
                "exclude_from_transactions": obj.get("exclude_from_transactions"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
            }
        )
        return _obj
