# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from lunchable.models.child_transaction_object import ChildTransactionObject
from lunchable.models.currency_enum import CurrencyEnum
from lunchable.models.update_transaction_object_amount import (
    UpdateTransactionObjectAmount,
)
from typing import Set
from typing_extensions import Self


class UpdateTransactionObject(BaseModel):
    """
    UpdateTransactionObject
    """  # noqa: E501

    id: Optional[StrictInt] = Field(
        default=None,
        description="System defined unique identifier of this transaction. Ignored if set.",
    )
    var_date: Optional[date] = Field(
        default=None, description="Date of transaction in ISO 8601 format", alias="date"
    )
    amount: Optional[UpdateTransactionObjectAmount] = None
    currency: Optional[CurrencyEnum] = Field(
        default=None,
        description='Three-letter lowercase currency code of the transaction in ISO 4217 format.<br> May not be updated on transactions that belong to a synced account with the "Allow Modifications to Transactions" property disabled.',
    )
    recurring_id: Optional[StrictInt] = Field(
        default=None,
        description="The unique identifier of the associated recurring item that this transaction matches.",
    )
    payee: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=140)]
    ] = Field(default=None, description="The new payee for the transaction. ")
    category_id: Optional[StrictInt] = Field(
        default=None,
        description="Unique identifier of the category for this transaction. Set this to 0 to clear the transaction's category.",
    )
    notes: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=350)]
    ] = Field(
        default=None,
        description="New notes for the transaction. Set this to an empty string to clear the existing notes. ",
    )
    manual_account_id: Optional[StrictInt] = Field(
        default=None,
        description='The unique identifier of the manual account associated with this transaction. Set this to zero to disassociate the transaction with an account. If set `plaid_account_id` may not also be set to a non zero value. Moving an existing transaction to to another account will not work if the transaction belongs to a synced account who\'s "Allow Modifications to Transactions" property is not set.',
    )
    plaid_account_id: Optional[StrictInt] = Field(
        default=None,
        description='The unique identifier of the plaid account associated with this transaction. If set `manual_account_id` may not also be set to a non zero value. Moving an existing transaction to to an existing Plaid account will not work if the account\'s "Allow Modifications to Transactions" property is not set.',
    )
    tag_ids: Optional[List[StrictInt]] = Field(
        default=None,
        description="A list of tag_ids for the tags associated with this transaction. If set, this property will overwrite any existing tags. Use `additional_tag_ids` to add tags to the existing transaction's tags. Set this to an empty array to remove all tags from a transaction. If set `additional_tag_ids` may not be set.",
    )
    additional_tag_ids: Optional[List[StrictInt]] = Field(
        default=None,
        description="A list of tag_ids for the tags associated with this transaction. If set, the tags listed in this property be added to any existing transaction tags. Use `tag_ids` to overwrite or clear transaction tags. If set `tag_ids` may not be set.",
    )
    external_id: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=75)]
    ] = Field(
        default=None,
        description="A user-defined external ID for the transaction. The update will fail if the transaction does not also have a `manual_account_id` or if there is already an existing transaction with the same `manual_account_id`/`external_id` combination.",
    )
    custom_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="User defined JSON data that can be set or cleared via the API.",
    )
    status: Optional[StrictStr] = Field(
        default=None,
        description="Status of the transaction, may be one of: - `reviewed`: User has reviewed the transaction, or it was automatically marked as reviewed due to reviewed recurring_item logic - `unreviewed`: User has not reviewed the transaction and it does not match any reviewed recurring_items. ",
    )
    to_base: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="System defined amount of this transaction in the user's primary currency. Ignored if set.",
    )
    is_pending: Optional[StrictBool] = Field(
        default=None,
        description="System defined flag set for pending transactions. Ignored if set.",
    )
    plaid_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="System set metadata from a Plaid account sync. Ignored if set.",
    )
    created_at: Optional[datetime] = Field(
        default=None,
        description="System defined date and time of when the transaction was created. Ignored if set.",
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="System defined date and time of when the transaction was last updated. Ignored if set.",
    )
    is_parent: Optional[StrictBool] = Field(
        default=None,
        description="System defined boolean indicating if this transaction was split. To split or unsplit a transaction use the `/transactions/split` endpoint. Ignored if set.",
    )
    children: Optional[List[ChildTransactionObject]] = Field(
        default=None,
        description="An array of child transactions that exists when a transaction has been split or if the transaction is a group. Split and Grouped transactions may not be modified using this API. Ignored if set.",
    )
    parent_id: Optional[StrictInt] = Field(
        default=None,
        description="A transaction ID if this is a split transaction. Split transactions may not be modified this API. Use the `transactions/split` endpoint instead. Ignored if set.",
    )
    is_group: Optional[StrictBool] = Field(
        default=None,
        description="System defined boolean indicating if this transaction represents a group of transactions. Grouped transactions may not be modified with this API. Use the `transactions/group` endpoint instead. Ignored if set.",
    )
    group_id: Optional[StrictInt] = Field(
        default=None,
        description="A transaction group ID if this transaction is part of a group. Grouped transactions may not be modified with this API. Use the `transactions/group` endpoint instead. Ignored if set.",
    )
    source: Optional[StrictStr] = Field(
        default=None,
        description="System defined original source of the transaction. Ignored if set. ",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "date",
        "amount",
        "currency",
        "recurring_id",
        "payee",
        "category_id",
        "notes",
        "manual_account_id",
        "plaid_account_id",
        "tag_ids",
        "additional_tag_ids",
        "external_id",
        "custom_metadata",
        "status",
        "to_base",
        "is_pending",
        "plaid_metadata",
        "created_at",
        "updated_at",
        "is_parent",
        "children",
        "parent_id",
        "is_group",
        "group_id",
        "source",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["reviewed", "unreviewed"]):
            raise ValueError("must be one of enum values ('reviewed', 'unreviewed')")
        return value

    @field_validator("source")
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(
            [
                "api",
                "csv",
                "manual",
                "merge",
                "plaid",
                "recurring",
                "rule",
                "split",
                "user",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('api', 'csv', 'manual', 'merge', 'plaid', 'recurring', 'rule', 'split', 'user')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateTransactionObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict["amount"] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict["children"] = _items
        # set to None if recurring_id (nullable) is None
        # and model_fields_set contains the field
        if self.recurring_id is None and "recurring_id" in self.model_fields_set:
            _dict["recurring_id"] = None

        # set to None if category_id (nullable) is None
        # and model_fields_set contains the field
        if self.category_id is None and "category_id" in self.model_fields_set:
            _dict["category_id"] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict["notes"] = None

        # set to None if manual_account_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.manual_account_id is None
            and "manual_account_id" in self.model_fields_set
        ):
            _dict["manual_account_id"] = None

        # set to None if plaid_account_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.plaid_account_id is None
            and "plaid_account_id" in self.model_fields_set
        ):
            _dict["plaid_account_id"] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict["external_id"] = None

        # set to None if custom_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.custom_metadata is None and "custom_metadata" in self.model_fields_set:
            _dict["custom_metadata"] = None

        # set to None if plaid_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.plaid_metadata is None and "plaid_metadata" in self.model_fields_set:
            _dict["plaid_metadata"] = None

        # set to None if parent_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_id is None and "parent_id" in self.model_fields_set:
            _dict["parent_id"] = None

        # set to None if group_id (nullable) is None
        # and model_fields_set contains the field
        if self.group_id is None and "group_id" in self.model_fields_set:
            _dict["group_id"] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict["source"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateTransactionObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "date": obj.get("date"),
                "amount": UpdateTransactionObjectAmount.from_dict(obj["amount"])
                if obj.get("amount") is not None
                else None,
                "currency": obj.get("currency"),
                "recurring_id": obj.get("recurring_id"),
                "payee": obj.get("payee"),
                "category_id": obj.get("category_id"),
                "notes": obj.get("notes"),
                "manual_account_id": obj.get("manual_account_id"),
                "plaid_account_id": obj.get("plaid_account_id"),
                "tag_ids": obj.get("tag_ids"),
                "additional_tag_ids": obj.get("additional_tag_ids"),
                "external_id": obj.get("external_id"),
                "custom_metadata": obj.get("custom_metadata"),
                "status": obj.get("status"),
                "to_base": obj.get("to_base"),
                "is_pending": obj.get("is_pending"),
                "plaid_metadata": obj.get("plaid_metadata"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "is_parent": obj.get("is_parent"),
                "children": [
                    ChildTransactionObject.from_dict(_item) for _item in obj["children"]
                ]
                if obj.get("children") is not None
                else None,
                "parent_id": obj.get("parent_id"),
                "is_group": obj.get("is_group"),
                "group_id": obj.get("group_id"),
                "source": obj.get("source"),
            }
        )
        return _obj
