# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Annotated, Self

from lunchable.models.create_category_request_object_children_inner import (
    CreateCategoryRequestObjectChildrenInner,
)


class UpdateCategoryRequestObject(BaseModel):
    """
    UpdateCategoryRequestObject
    """  # noqa: E501

    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = (
        Field(
            default=None,
            description="If set the new name of the category. Must be between 1 and 100 characters.",
        )
    )
    description: Optional[
        Annotated[str, Field(min_length=0, strict=True, max_length=200)]
    ] = Field(
        default=None,
        description="If set the new description of the category. Must not exceed 200 characters.",
    )
    is_income: Optional[StrictBool] = Field(
        default=None,
        description="If set will indicate if this category will be treated as income.",
    )
    exclude_from_budget: Optional[StrictBool] = Field(
        default=None,
        description="If set will indicate if this category will be excluded from budgets.",
    )
    exclude_from_totals: Optional[StrictBool] = Field(
        default=None,
        description="If set will indicate if this category will be excluded from totals.",
    )
    archived: Optional[StrictBool] = Field(
        default=None, description="If set will indicate if this category is archived."
    )
    group_id: Optional[StrictInt] = Field(
        default=None,
        description="If set to the ID of an existing category group, and this category is not itself a category group, this category will be a child of the specified group.",
    )
    is_group: Optional[StrictBool] = Field(
        default=False,
        description="If set, this attribute may not be set to a value that is different than the current status of the category or category group. In other words, this API may not be used to convert a category to a category group or vice versa.",
    )
    children: Optional[List[CreateCategoryRequestObjectChildrenInner]] = Field(
        default=None,
        description="The list of existing category objects, or existing category IDs or names of new categories to add to the new category group. This attribute should only be set if modifying an existing category group.<br> The categories or IDs specified must already exist and not belong to an existing category group. Categories that already belong to another category group will be moved. If strings are specified, they will be used as the names of new categories that will be added to the new category group. The request will fail if any names are the same as the name of an existing category.<br> It is permissible to provide both full category objects and IDs as well as strings for names in the same request.",
    )
    id: Optional[StrictInt] = Field(
        default=None,
        description="System defined unique identifier for the category. Ignored if set.",
    )
    archived_at: Optional[StrictStr] = Field(
        default=None,
        description="System set date and time of when the category was last archived (in the ISO 8601 extended format). Ignored if set.",
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="System set date and time of when the category was last updated (in the ISO 8601 extended format). Ignored if set.",
    )
    created_at: Optional[datetime] = Field(
        default=None,
        description="System set date and time of when the category was created (in the ISO 8601 extended format). Ignored if set. (in the ISO 8601 extended format). Ignored if set.",
    )
    order: Optional[StrictInt] = Field(
        default=None,
        description="System or GUI set index specifying the position in which the category is displayed on the categories page in the Lunch Money GUI. Ignored if set.",
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "description",
        "is_income",
        "exclude_from_budget",
        "exclude_from_totals",
        "archived",
        "group_id",
        "is_group",
        "children",
        "id",
        "archived_at",
        "updated_at",
        "created_at",
        "order",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateCategoryRequestObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict["children"] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        # set to None if group_id (nullable) is None
        # and model_fields_set contains the field
        if self.group_id is None and "group_id" in self.model_fields_set:
            _dict["group_id"] = None

        # set to None if is_group (nullable) is None
        # and model_fields_set contains the field
        if self.is_group is None and "is_group" in self.model_fields_set:
            _dict["is_group"] = None

        # set to None if archived_at (nullable) is None
        # and model_fields_set contains the field
        if self.archived_at is None and "archived_at" in self.model_fields_set:
            _dict["archived_at"] = None

        # set to None if order (nullable) is None
        # and model_fields_set contains the field
        if self.order is None and "order" in self.model_fields_set:
            _dict["order"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateCategoryRequestObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "description": obj.get("description"),
                "is_income": obj.get("is_income"),
                "exclude_from_budget": obj.get("exclude_from_budget"),
                "exclude_from_totals": obj.get("exclude_from_totals"),
                "archived": obj.get("archived"),
                "group_id": obj.get("group_id"),
                "is_group": obj.get("is_group")
                if obj.get("is_group") is not None
                else False,
                "children": [
                    CreateCategoryRequestObjectChildrenInner.from_dict(_item)
                    for _item in obj["children"]
                ]
                if obj.get("children") is not None
                else None,
                "id": obj.get("id"),
                "archived_at": obj.get("archived_at"),
                "updated_at": obj.get("updated_at"),
                "created_at": obj.get("created_at"),
                "order": obj.get("order"),
            }
        )
        return _obj
