# coding: utf-8

"""
Lunch Money API - v2

## Overview This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.   The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the  [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.8.0
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing_extensions import Annotated, Self


class UpdateTagRequestObject(BaseModel):
    """
    UpdateTagRequestObject
    """  # noqa: E501

    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = (
        Field(
            default=None,
            description="If set the new name of the category. Must be between 1 and 100 characters.",
        )
    )
    description: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(
        default=None,
        description="If set the new description of the category. Must not exceed 200 characters.",
    )
    archived: Optional[StrictBool] = Field(
        default=None, description="If set will indicate if this category is archived."
    )
    id: Optional[StrictInt] = Field(
        default=None,
        description="System defined unique identifier for the category. Ignored if set.",
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="System set time the tag was last updated. Ignored if set",
    )
    created_at: Optional[datetime] = Field(
        default=None, description="System set time the tag was created. Ignored if set."
    )
    archived_at: Optional[datetime] = Field(
        default=None,
        description="System set time the tag was archived. Ignored if set.",
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "description",
        "archived",
        "id",
        "updated_at",
        "created_at",
        "archived_at",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateTagRequestObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        # set to None if archived_at (nullable) is None
        # and model_fields_set contains the field
        if self.archived_at is None and "archived_at" in self.model_fields_set:
            _dict["archived_at"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateTagRequestObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "description": obj.get("description"),
                "archived": obj.get("archived"),
                "id": obj.get("id"),
                "updated_at": obj.get("updated_at"),
                "created_at": obj.get("created_at"),
                "archived_at": obj.get("archived_at"),
            }
        )
        return _obj
