# coding: utf-8

"""
Lunch Money API - v2

This is a version of the Lunch Money API described using the the OpenAPI 3.X specification.  The goal of this project is to validate an \"API Design First\" approach for the Lunch Money API, which should allow us to gather developer feedback prior to implementation in order to develop API endpoints more quickly.  This version of the API will differ from the existing v1 beta version. For more information on the changes please see the [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog)  Some useful links: - [Current v1 Lunch Money API Documentation](https://lunchmoney.dev) - [v2 API Changelog](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/changelog) - [OpenAPI API YAML Specification](https://lm-v2-api-mock-data-f24357049a1b.herokuapp.com/v2/openapi/) - [Awesome Lunch Money Projects](https://lunchmoney.dev/#awesome-projects)

The version of the OpenAPI document: 2.7.4
Contact: devsupport@lunchmoney.app
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from lunchable.models.currency_enum import CurrencyEnum
from typing import Set
from typing_extensions import Self


class UserObject(BaseModel):
    """
    UserObject
    """  # noqa: E501

    name: StrictStr = Field(description="User's name")
    email: StrictStr = Field(description="User's email")
    id: StrictInt = Field(description="Unique identifier for user")
    account_id: StrictInt = Field(
        description="Unique identifier for the associated budgeting account"
    )
    budget_name: StrictStr = Field(
        description="Name of the associated budgeting account"
    )
    primary_currency: CurrencyEnum = Field(
        description="Primary currency from user's settings"
    )
    api_key_label: Optional[StrictStr] = Field(
        description="User-defined label of the developer API key used. Returns null if nothing has been set."
    )
    __properties: ClassVar[List[str]] = [
        "name",
        "email",
        "id",
        "account_id",
        "budget_name",
        "primary_currency",
        "api_key_label",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if api_key_label (nullable) is None
        # and model_fields_set contains the field
        if self.api_key_label is None and "api_key_label" in self.model_fields_set:
            _dict["api_key_label"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "email": obj.get("email"),
                "id": obj.get("id"),
                "account_id": obj.get("account_id"),
                "budget_name": obj.get("budget_name"),
                "primary_currency": obj.get("primary_currency"),
                "api_key_label": obj.get("api_key_label"),
            }
        )
        return _obj
