# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: OpenAPI Client Generator

on:
    workflow_dispatch:
    push:
        branches:
            - v2
    schedule:
        - cron: "0 12 * * 5"

jobs:
    generate:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                  ref: v2
            - name: setup-node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: setup-java
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: "21"
            - name: setup-python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"
            - name: npm-install
              run: npm clean-install
            - name: audit-signatures
              run: npm audit signatures
            - name: generate-spec
              run: npm run spec
            - name: openapi-version
              id: version
              uses: mikefarah/yq@master
              with:
                  cmd: cat openapi.yaml | yq -r .info.version
            - name: delete-clients
              run: rm -rf clients/
            - name: generate
              run: npm run generate
            - name: git-add
              run: git add --all
            - name: pre-commit
              continue-on-error: true
              uses: pre-commit/action@v3.0.1
            - name: pull-request
              uses: peter-evans/create-pull-request@v7
              with:
                  add-paths: openapi.yaml,clients
                  commit-message: ✨ lunchmoney openapi spec v${{ steps.version.outputs.result }} - ${{ github.run_id }}
                  branch: openapi/v${{ steps.version.outputs.result }}/${{ github.run_id }}
                  delete-branch: true
                  title: ✨ lunchmoney openapi spec v${{ steps.version.outputs.result }}
                  body: "## ✨ LunchMoney Developer API v${{ steps.version.outputs.result }}"
